### ISSUE TITLE
WPF Changing MenuSeparator Visibility crashes the app

### ISSUE THREAD

**Issue by cra0zy** [mono/xwt#533] opened 2015-07-18 12:28 UTC
Changing MenuSeperator Visibility in WPF crashes the app with NullReferenceException

**Comment by sevoku** [comment] 2015-07-20 09:09
It looks like most properties use the SWC.MenuItem reference, but a separator is not a MenuItem.

**Comment by sevoku** [comment] 2015-07-20 17:55
duplicate of #364

**Closed** 2015-07-20 17:55 UTC
Labels: confirmed-bug, WPF

**Comment by cra0zy** [comment] 2015-07-20 18:07
thanks for the quick fix
